CREATE DATABASE db_lingomq_words_dev;
CREATE DATABASE db_lingomq_achievements_dev;
CREATE DATABASE db_lingomq_notifications_dev;
CREATE DATABASE db_lingomq_topics_dev;
CREATE DATABASE db_lingomq_finances_dev;
CREATE DATABASE db_lingomq_authentication_dev;
CREATE DATABASE db_lingomq_identity_dev;